version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

    groups:
      action-updates:
        applies-to: version-updates
        patterns:
          - ".*"

  - package-ecosystem: "gomod"
    directories:
      - "/contrib/charts/dragonfly"
      - "/tools/replay"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

    groups:
      gomod-security:
        applies-to: security-updates
        patterns:
          - ".*"

  - package-ecosystem: "pip"
    directories:
      - "/tests/dragonfly"
      - "/tools"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

    groups:
      pip-security:
        applies-to: security-updates
        patterns:
          - ".*"
