version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
        update-types: 
          - "security"
    groups:
      dev-dependencies:
        applies-to: security-updates
        patterns:
          - ".*"

  - package-ecosystem: "gomod"
    directories:
      - "/contrib/charts/dragonfly"
      - "/tools/replay"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
        update-types: 
          - "security"
    groups:
      dev-dependencies:
        applies-to: security-updates
        patterns:
          - ".*"

  - package-ecosystem: "pip"
    directories:
      - "/tests/dragonfly"
      - "/tools"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
        update-types:
          - "security"
    groups:
      dev-dependencies:
        applies-to: security-updates
        patterns:
          - ".*"
