version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "direct"
      

  - package-ecosystem: "gomod"
    directories:
      - "/contrib/charts/dragonfly"
      - "/tools/replay"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "direct"
        update-type: "security"

  - package-ecosystem: "pip"
    directories:
      - "/tests/dragonfly"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "direct"
        update-type: "security"
